// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Assets {
  const Assets._();
  static const String assets_avatar_jpg = 'assets/avatar.jpg';
}
